** Traditional comparisons
cite:Craig1988 compares the opportunistic style of reasoning exhibited by the blackboard to forwards and backwards reasoning models.

In forward reasoning systems inference rules are applied from an initial state toward a goal.
This is usually done in a systematic way such as breadth or depth first search.

Backward reasoning systems such as Prolog/Kanren/ *One of Charnley's solvers* solve problems by chaining inference rules backwards from a goal towards a given initial state.

In opportunistic systems inference rules are said to be applied at the most opportune moment. See section X.

This placement whilst entirely valid and characterises the peculiar potential of blackboard like systems was perhaps influenced by popular means of system construction at the time -  simply referring to familiar means of building systems and simply situates them relative to familiar signposts for contemporaries.

** Why am I not comparing to Logic programming/backwards reasoning today? 
Unfortunately the backwards reasoning approach to combining reasoning systems is now out of reach to developers which seek to combine others work.

Most of the available software modules are expressed in languages that does not exhibit the *reversibility* logic programming languages and manually work is often not undertaken to make the system exhibit this property.
Business/academic requirements often dictate that only one path through an encapsulated piece of logic be described implemented.
This means that existing software modules cannot be easily be utilised in backward reasoning systems.

A webservice typically only allows forward reasoning using it's capabilities. 
The same is true of the modules bundled up in FloWr, ConcreteFlows, BB Poetry system and Slant.

Modules provided only operate in /if this then that/ we don't get /if that then this/ for free.
i.e. modules only useful for forward inference.

** Why a I not comparing to forward reasoning systems?

Perhaps I am? Each FloWr workflows expresses one path through a forward reasoning system?

Bredth/depth first recombination of functions is not performed. Genetic programming was planned instead in FloW

