* FACE or ACE?

** Abstract
** Introduction

Computational processes are only useful when we are able to communicate with it in order to assign it tasks, and understand the information it returns.

 Recent measures for computational creativity have such as FACE have looked to reward systems that can frame there output.

 Colton et al. have claimed in a number of papers that in order for a systems to be "taken seriously as creative entities in the cultural world" they should be to be fitted with a "story generator" which produces not only framing information but that can be drawn in to a dialogue in which it will answer any questions asked of it cite:colton-goodwin-veale:2012 cite:AlisonPeaseandSimonColton2011. 

In fact the field of AI in general and regularly with in CC there have been calls for systems to be enabled with the ability to converse using natural language cite:Baroni2017 

Veale?

** Is framing info good
   
 Whilst framing information can add value to creative acts, allowing agents unfamiliar with a medium, practice piece, or computing concepts such as programming or computational creativity evaluation to situate pieces it produces along side others it knows about.

Monalisa - is she similing or not? 
Much of the value considered in the idea image is open to interpretation. Artists did not provide one for us.

Vasari - the original art critic observed that jesters and musicians were employed to entertain
Freud's interpretation that image reflects Leonardo's memory of his mother cite:Barolsky1991

Other argue that she's simply hiding her front teeth cite:Borkowski1992

Indeed this ambiguity still drives scientific research in to the perception of smiling today.

Had Leonardo provided an explanation of what exactly she's doing it's questionable whether this work would be the focus of such discussions today cite:Kontsevich2004.

** Accessability of language

A language only reveals the meaning within its utterances to those with some fluency in it. 
The framing information required of arts students is often inaccessible to those with out arts degrees.
If framing information is in French it is inaccessible to English speaker.
Many acts of genius are limited to understanding by peers.
Certain mental disorders negate access to body or spoken language.
Disabled children - Guild Hall museum - Blind people

** Do we have enough already?
*** What framing info do we get for cheap
**** Understanding what a program has done
***** Explaining processes with code
****** code self documenting
******* Human readability
  How far have we really come with regards to human readability?
  Relatively recent innovations such as HTML, XML Schema 
  seem to have been distracted from the original goal of making data more portable
  More important that we produce measurable artefacts that easily translate in to measurable artefacts for our bosses - jar file - check!, schema check!
  In some way much of the current state of the art in these areas has begun to look back toward what we had back in the fifties - a totally uniform means of expressing the shape of data 
  (EDN <- LISP, JSON <spec <- Regular expressions) 

******* Knuth - Literate programming
  Knuth argued that programs should be considered works of literature and that there purpose should not just be to instruct a machine on how to operate but also explain to human beings what we want a computer to do.

  Whilst he focused on improving comprehensibility through the incorporation of natural language in to program descriptions with his WEB system

  cite:Knuth
******* Dijkstra - structured programming
  cite:Dijkstra noted in the seventies that the conceptual gap between the static program and the corresponding computations

  The von Neuman architecture only allows the execution of a single change in state at a time and all computations can be viewed as the sequential completion of simpler steps.

  Even tools like flow charts can be used to comprehensibly describe a system

***** DSL

***** Logging
****** Unexplaiable neural networks
******* Deep dream - it's hard to tell what each layer is responsible for
******* when layers are visualised - meaning is clearer

****** Self explaining evolutionary histories

**** Conversing with computers with code
***** Interaction fulfilled by REPL

 We need to get in to a dialogue

  The closest we've come to conversing in an interactive manner with a machine could be said to be working with a machine at the REPL.
  Quick feedback. 
  Machine and user in tight feedback loop. 
  Talking in the same language.
  Probe
  Turing tests


** Source code vs thought experiments
Possibility of deeper interaction with code than with people.
Thought experiments can be replicated.
In English language there is room for ambiguity, misinterpretation and loss of meaning and different interpretations from different people.
Code is an expression in languages that can not be misinterpreted. the system always does what you said.

Randomness

** lieing/honesty window dressing

Live coding 
- Framing info shown
  - Confuse audience in to believing that something clever has happened.

Magic tricks  

Distracts from the creative act

** New forms of intelligence/creativity
Regularily claimed that intelligence/creativity are not human only phenoma
Expecting non-human to use human specific language seems silly.

** autonomy vs framing information
   Colton claims more.

*** Hiding finger prints is the opposite of framing
  cite:Ventura2016 argues that as we move towards systems that can autonomously creative systems should aim to hide the finger prints of there creators believing that a process of 'Inception' may be used to inject greater nuance and depth in to a generalised process.

 Keith Row - revealing (or lack of) process

** Random notes

Harry Frankfurt - on bullshit
George Lewis - multi-domincance in systems

ML is obsessed with multiple examples
Generalise from one example
- Use knowledge of space around implementation
- Repurpose

Play first/learning later

Antrhropamorphise

We can ask artists to contextualise

Epistomology
Justified 
- protect
- post structuralist
- Questioning from Turing
  - open to be asked questions

- Painting fool
dishonesty
window dressing

Air traffic communications

** Shifting goal posts

*** AI
Chess not good enough
Driving not good enough
Tacit knowledge

Searle objection - Chinese box
Minds, brains and programs
- System can speak english

*** Arty farty

 Labour
 Frame work in same means as working class

 Success measured in the galleries

 Death of the author
 Framing is done viewer - Roland Barthes. Interpretation
 Pierre Bordieux - technocrat

    Why do we need to placate the art critics?

 It's arguable whether existing in artists in a particular domain do have a stake in deciding whether or not software can be creative.

 We seem to borrow much from post-modernists cannons on interpretation of art work.

 It seems we have not yet fully understood the post-modern doctrine.

 We understand that an artist will rebel against aesthetic constraints cite:colton:2008a but seem to have misunderstood whats been said about interpretation

 Whilst the issue of *latent heat* persists "We can only quarrel with one or another means of defense. Indeed, we have an obligation to overthrow any means of defending and justifying art which becomes particularly obtuse or onerous or insensitive to contemporary needs and practice." 
 cite:Sontag1966

** Discussion
** are we modelling more than we need to?

To what extent should we be imitating artists/scientists?

*** DIFI?
People interpret work in contexts
Can't be controlled
preconceptions
read FRAME and re-frame anyway

Swap art crtitic for Press/audience/

Is the F suitable for all types of C?
F is just an E

interaction vs framing vs promotion
professional and ameteuer

*** everyday creativity

creative promoter
doodlers/sat in bedrooms

** Recommendations
*** reproducible
*** Open source
*** Well documented
*** High level
*** Specifications
*** Providing services

** Conclusion
   framing info can be a distraction

within our research outputs there's a great many sources of framing info

  IT"S MY BELIEF THAT FRAMING INFORMATION SHOULD NOT BE USED TO INDICATE HOW CREATIVE A SYSTEM IS BEING UNLESS SAID FRAMING INFORMATION IS CREATED CREATIVELY

Whilst involving as many participants is extremely important we should feel free to develop systems that aren't concerned with the perception of others 

historical web art
